---
- name: have us locale
  locale_gen: name=en_US.UTF-8 state=present

- name: lc_all 
  lineinfile: dest=~/.bashrc line='export LC_ALL="en_US.UTF-8"'
      
- name: lc and that
  lineinfile: dest=~/.bashrc line='export LC_CTYPE="en_US.UTF-8"'

- name: have node thing set up 
  shell: "curl -sL https://deb.nodesource.com/setup | sudo bash -" 

- name: have open port 80 to the world (website) 
  sudo: yes
  shell: iptables -A INPUT -p tcp --dport 80 -j ACCEPT

- name: have open port 8080 to the world (webhook) 
  sudo: yes
  shell: iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
  
- name: have a bunch of different apt packages
  sudo: yes    
  apt: name={{ item }} 
  with_items: 
     - make
     - gcc
     - nodejs
     - git 
     - apache2

- name: have rvm and that jazz
  sudo: yes
  shell: "\\curl -sSL https://get.rvm.io | bash -s stable"

# you may need to run
# sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
# on your server to get the oneliner above to work. 

- name: let rvm do its thing with packages and that 
  sudo: yes
  shell: "rvm autolibs enable"
  environment:
        PATH: /usr/local/rvm/bin/:{{ ansible_env.PATH }} 

- name: have ruby
  sudo: yes
  shell: "rvm install ruby-1.9.3-p551 --with-opt-dir=/usr/local/ssl"
  environment:
        PATH: /usr/local/rvm/bin/:{{ ansible_env.PATH }} 

- name: have correct version of ruby set up 
  sudo: yes
  shell: "rvm --default use 1.9.3"
  environment:
        PATH: /usr/local/rvm/bin/:{{ ansible_env.PATH }} 

- name: have jekyll installed
  sudo: yes 
  shell: gem install jekyll rdiscount json executable="/bin/bash"
  environment:
        PATH: /usr/local/rvm/bin/:/usr/local/rvm/rubies/ruby-1.9.3-p551/bin/:{{ ansible_env.PATH }} 
      
- name: have forever installed 
  sudo: yes 
  npm: name=forever global=yes

- name: have moment installed
  sudo: yes
  npm: name=moment global=yes

- name: have jekyll-hook repo 
  sudo: yes
  git: repo=https://github.com/developmentseed/jekyll-hook.git dest=/jekyll-hook

- name: have npm configured correctly 
  shell: npm config set registry http://registry.npmjs.org/

- name: have jekyll-hook installed
  shell: npm install chdir=/jekyll-hook

- name: have jekyll-hook config file
  sudo: yes 
  copy: src=config.json dest=/jekyll-hook 

- name: have correct publish script 
  sudo: yes
  copy: src=publish.sh dest=/jekyll-hook/scripts/ force=yes

- name: have cs-lunch website repo
  sudo: yes
  git: repo=https://github.com/fjukstad/cs-lunch.git dest=/lunch

- name: have built the webpage
  sudo: yes 
  shell: "jekyll build -s /lunch -d /var/www" 
  environment:
        PATH: /usr/local/rvm/bin/:/usr/local/rvm/rubies/ruby-1.9.3-p551/bin/:{{ ansible_env.PATH }} 
 
- name: have apache start on boot 
  sudo: yes
  shell: update-rc.d apache2 defaults

- name: have restart apache service
  sudo: yes 
  service: name=apache2 state=restarted 

#- name: have jekyll-hook started 
#  sudo: yes
#  shell: forever start jekyll-hook.js chdir=/jekyll-hook 
