# Site settings
title: CS-lunch
# email: bjorn@cs.uit.no, einar@cs.uit.no
description: > # this means to ignore newlines until "baseurl:"
    This is the Department of Computer Science lunch seminar series. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lunch.cs.uit.no" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
